# Generated by Django 4.0.2 on 2022-02-06 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('socket', models.BooleanField(null=True)),
                ('no_of_sockets', models.IntegerField(null=True)),
                ('image_url', models.TextField(null=True)),
            ],
        ),
    ]
