# Generated by Django 4.0.2 on 2022-02-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='no_of_sockets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='socket',
            field=models.BooleanField(null=True),
        ),
    ]
