# Generated by Django 4.0.2 on 2022-02-06 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('occupation', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('shop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('userType', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.shops')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.type'),
        ),
    ]
