# Generated by Django 4.0.2 on 2022-02-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='shop_name',
        ),
    ]
