# Generated by Django 4.0.2 on 2022-02-06 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        ('users', '0003_account_email_account_first_name_account_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='shop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.shops'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('shop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.shops')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.account')),
            ],
        ),
    ]
