# Generated by Django 4.0.2 on 2022-02-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
