# Generated by Django 4.0.2 on 2022-02-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_review_rating_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='surname',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
